### PR TITLE
BUG: Fix MSVC 15 2017+ OpenBLAS compilation

### PR DESCRIPTION
**Pull request by larsoner**
Let's debug https://github.com/xianyi/OpenBLAS/issues/3661#issuecomment-1162828486 / https://github.com/Reference-LAPACK/lapack/issues/683

### CODE REVIEW

**Comment by larsoner** [comment]
Okay failure replicated in https://github.com/openmeeg/openmeeg/runs/7004260308 :
```
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
  Checking Build System
  Building Custom Rule D:/a/openmeeg/openmeeg/OpenMEEGMaths/CMakeLists.txt
  vector.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include\xlocale(319): warning C45[30](https://github.com/openmeeg/openmeeg/runs/7004260308?check_suite_focus=true#step:15:31): C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
d:\a\openmeeg\openmeeg\openblas\64\include\lapack.h(104): error C2143: syntax error: missing ',' before '*' [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
d:\a\openmeeg\openmeeg\openblas\64\include\lapack.h(106): error C2143: syntax error: missing ',' before '*' [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
d:\a\openmeeg\openmeeg\openblas\64\include\lapack.h(107): error C2143: syntax error: missing ',' before '*'
```
Now to try the patch that was suggested...

**Comment by larsoner** [comment]
All that seems to [have done](https://github.com/openmeeg/openmeeg/runs/7004511582?check_suite_focus=true) is shifted the errors down by 4 lines:
```
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
  Checking Build System
  Building Custom Rule D:/a/openmeeg/openmeeg/OpenMEEGMaths/CMakeLists.txt
  vector.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.16.27023\include\xlocale(319): warning C45[30](https://github.com/openmeeg/openmeeg/runs/7004511582?check_suite_focus=true#step:15:31): C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
d:\a\openmeeg\openmeeg\openblas\64\include\lapack.h(108): error C2143: syntax error: missing ',' before '*' [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
d:\a\openmeeg\openmeeg\openblas\64\include\lapack.h(110): error C2143: syntax error: missing ',' before '*' [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
```

**Comment by martin-frbg** [comment]
C_MSVC is what OpenBLAS uses... Note there is a similar definition for complex double a few lines down that will also need patching

**Comment by larsoner** [comment]
> C_MSVC is what OpenBLAS uses...

From a quick look I only see 2 pages of Google search results for `"C_MSVC"`, so it seems *very* rare to use it. Is it possible it's actually incorrect there?

I'll push a commit to use `_MSC_VER` since it seems to be a popular option for people to use

**Comment by martin-frbg** [comment]
Anyway that idea needs more work than I anticipated - Microsoft's  _Fcomplex is a struct which is probably why the define is not going to work.

**Comment by larsoner** [comment]
There are also a lot of:
```
d:\a\openmeeg\openmeeg\openblas\64\include\lapack.h(108): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
```
which makes it seem like MSVC is still interpreting this as a C++ header rather than a C one, despite the `extern` :(

**Pull request merged**
