### PR TITLE
Attempt to fix conda failure in appveyor

### PR DESCRIPTION
**Pull request by papadop**
On internet two solution are proposed:
- downgrade to conda 4.3.34
- avoid path manipulation and instead call a script (see https://github.com/conda/conda/issues/8836)

Attempting the last one.

### CODE REVIEW

**Comment by papadop** [comment]
Seems appveyor is repaired...
Why travis fails is a nonsense and probably just a temporary network problem.

**Comment by papadop** [comment]
My last comment means I think we can merge.... And then evaluate the python branch state on windows... I'm a little bit afarid as I have seen that we use VS 2015 and I wonder whether it has the new C++ features we use (or we will have to upgrade the compiler).

**Comment by agramfort** [comment]
Perfect thanks @papadop

**Comment by massich** [comment]
great Job!

**Pull request merged**
