### PR TITLE
[MRG] new build system

### PR DESCRIPTION
**Pull request by massich**
This PR takes over #265 to allow pushing to openmeeg/openmeeg_packages

### CODE REVIEW

**Comment by agramfort** [comment]
All green !

Ok for you @papadop ?

**Comment by agramfort** [comment]
how everything is green:

https://travis-ci.org/openmeeg/openmeeg_packages/branches

I propose to merge, then open issues to put back openblas support as well as CGAL

**Comment by massich** [comment]
Just in case we ever want to go Docker with the build system to speed up etc, this is a nice example:
https://github.com/pptacher/probabilistic_robotics/blob/944bae58db62c1a37cd437cba5730d316e15f4e2/ch13_the_fastslam_algorithm/src/cpp/Dockerfile

```sh
RUN wget --no-check-certificate https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB
RUN sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
RUN apt-get update
RUN apt-get install  -y --no-install-recommends intel-mkl-2018.2-046
RUN rm -rf /var/lib/apt/lists/*
```

**Comment by agramfort** [comment]
as an alternative to downloading mkl ?

>

**Comment by massich** [comment]
yes. I just came across it while fighting matio. IMNHO its a good alternative. 

We actually discussed similar solutions and we postponed them (and I agree). I just wanted to add it here for completeness. It does nothing in my notes. It's much better placed here. So that when we check the blame of mkl we can see its comming from this PR, etc..

**Pull request merged**
