### PR TITLE
Issuefix350

### LINKED ISSUE #350: error if center of interface is in the negative domain
On a surely closed interface I get the following error:
> Interface "3" is not closed ! 
> Please correct a mesh orientation when defining the interface in the geometry file. 

The bbcenter is out of the interface, due to an erroneous bounding box.
In interface.cpp the xmax,ymax and zmax are wrongly initialized to the numerical minimum, which is close to zero and not to minus infinity. This leads to erroneous bounding boxes if the center of an interface is in the negative domain for any coordinate. I have a branch solving this and will file a pull request, soon.

### PR DESCRIPTION
**Pull request by DanielMiklody**
closes #350

### CODE REVIEW

**Comment by DanielMiklody** [comment]
sorry some things got mixed up here. Need to recommit

**Comment by agramfort** [comment]
@DanielMiklody thanks. Yes please limit the PR to fix of issue.

We'll see for the rest with another PR. thanks

**Comment by DanielMiklody** [comment]
Ok, this is it 1 file 3 lines changed.

**Comment by agramfort** [comment]
thx a lot @DanielMiklody

**Pull request merged**
