### PR TITLE
add an option so that not all libs (vtk, cgal,...) are always copied …

### PR DESCRIPTION
**Pull request by eolivi**
…on Mac

### CODE REVIEW

**Comment by eolivi** [comment]
this does not solved problems discussed https://github.com/openmeeg/openmeeg/pull/209
I would need a mac....

**Comment by agramfort** [comment]
this just adds an option right? it does not solve the problem of missing vtk lib?

**Comment by eolivi** [comment]
right.
I don't get why you had this missing libvtkDomainsChemistryOpenGL2-7.1.1.dylib
I'll check again on thi ci but this is not one library we use.
anyway for this + OpenMP, I would need access to a (recent) mac. @papadop can we borrow one anywhere ? I come tomorrow ?

**Comment by agramfort** [comment]
forget about OpenMP for now on mac. Make it a separate PR.

regarding vtk extra I don't know. Here is what ldd tells me after
installing vtk on my mac:

```
alex@:openmeeg_brew2$ ldd src/om_assemble
src/om_assemble:
/Users/alex/work/bin/openmeeg_brew2/libs/OpenMEEG/src/libOpenMEEG.1.dylib
(compatibility version 1.0.0, current version 1.1.0)
/usr/local/opt/openblas/lib/libopenblasp-r0.2.19.dylib (compatibility
version 0.0.0, current version 0.0.0)
/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
/usr/lib/libexpat.1.dylib (compatibility version 7.0.0, current version
8.0.0)
/usr/local/opt/vtk/lib/libvtkDomainsChemistryOpenGL2-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/lib/libjpeg.8.dylib (compatibility version 13.0.0, current
version 13.0.0)
/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 46.0.0,
current version 46.0.0)
/usr/local/opt/libtiff/lib/libtiff.5.dylib (compatibility version 8.0.0,
current version 8.6.0)
/usr/local/opt/vtk/lib/libvtkFiltersFlowPaths-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersGeneric-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersHyperTree-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersParallelImaging-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersPoints-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersProgrammable-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersPython-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/Python.framework/Versions/2.7/Python
(compatibility version 2.7.0, current version 2.7.10)
/usr/local/opt/vtk/lib/libvtkWrappingPython27Core-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersSMP-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersSelection-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersTexture-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersVerdict-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkverdict-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkGeovisCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkproj4-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOAMR-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/hdf5/lib/libhdf5.101.dylib (compatibility version 102.0.0,
current version 102.0.0)
/usr/local/lib/libsz.2.0.0.dylib (compatibility version 3.0.0, current
version 3.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version
1238.0.0)
/usr/local/opt/hdf5/lib/libhdf5_hl.100.dylib (compatibility version
101.0.0, current version 101.1.0)
/usr/local/opt/vtk/lib/libvtkIOEnSight-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOExodus-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/netcdf/lib/libnetcdf_c++.4.dylib (compatibility version
7.0.0, current version 7.0.0)
/usr/local/opt/netcdf/lib/libnetcdf.11.dylib (compatibility version 11.0.0,
current version 11.4.0)
/usr/local/opt/vtk/lib/libvtkIOExport-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingGL2PSOpenGL2-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkgl2ps-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOImport-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOInfovis-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version
10.9.0)
/usr/local/opt/vtk/lib/libvtkIOLSDyna-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOMINC-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOMovie-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkoggtheora-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOPLY-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOParallel-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkjsoncpp-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOParallelXML-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOSQL-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtksqlite-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOTecplotTable-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOVideo-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingMorphological-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingStatistics-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingStencil-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkInfovisBoostGraphAlgorithms-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkInteractionImage-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingContextOpenGL2-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingFreeTypeFontConfig-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingImage-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingLOD-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingVolumeOpenGL2-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkViewsContext2D-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkViewsInfovis-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkDomainsChemistry-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersAMR-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersParallel-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkexoIIc-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOGeometry-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIONetCDF-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkParallelCore-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOLegacy-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingOpenGL2-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility
version 1.0.0, current version 22.0.0)
/usr/local/opt/vtk/lib/libvtkglew-7.1.1.dylib (compatibility version 1.0.0,
current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingMath-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkChartsCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingContext2D-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersImaging-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkInfovisLayout-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkInfovisCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkViewsCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkInteractionWidgets-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersHybrid-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingGeneral-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingSources-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersModeling-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingHybrid-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOImage-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkDICOMParser-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkmetaio-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkInteractionStyle-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersExtraction-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersStatistics-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingFourier-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkalglib-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingAnnotation-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingColor-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingVolume-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkImagingCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOXML-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOXMLParser-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkIOCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingLabel-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingFreeType-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkRenderingCore-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonColor-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersGeometry-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersSources-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersGeneral-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonComputationalGeometry-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkFiltersCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonExecutionModel-7.1.1.dylib
(compatibility version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonDataModel-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonTransforms-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonMisc-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonMath-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonSystem-7.1.1.dylib (compatibility
version 1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkCommonCore-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/usr/local/opt/vtk/lib/libvtksys-7.1.1.dylib (compatibility version 1.0.0,
current version 1.0.0)
/usr/local/opt/vtk/lib/libvtkfreetype-7.1.1.dylib (compatibility version
1.0.0, current version 1.0.0)
/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
(compatibility version 1.0.0, current version 48.0.0)
/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
(compatibility version 1.0.0, current version 775.9.7)
/Users/alex/work/bin/openmeeg_brew2/libs/OpenMEEGMaths/src/libOpenMEEGMaths.1.dylib
(compatibility version 1.0.0, current version 1.1.0)
/usr/local/opt/libmatio/lib/libmatio.4.dylib (compatibility version 8.0.0,
current version 8.0.0)
/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version
307.4.0)
```

**Comment by agramfort** [comment]
this is not redundant with ENABLE_PACKAGING option? You imagine packaging on mac without copying the necessary libs?

does this fix the VTK libs problem?

**Comment by eolivi** [comment]
> This is not redundant with ENABLE_PACKAGING option?  You imagine packaging on mac without copying the necessary libs?

right, so that we can package either providing All Extern Libs (vtk, ...), or simply the openmeeg ones.
Is it useless ? I thought brew when making a new formula would build and then package ?

(this is only on Mac)

**Comment by eolivi** [comment]
Either I copy all vtk libs which make a lot, or we ship without vtk ?

**Comment by agramfort** [comment]
brew does not package. I think it does a make install but maybe make
install means also copying all dylibs?

I am fine releasing without vtk on mac and tell people to use brew with vtk
option to have openmeeg with vtk on mac (same is true for CGAL).

**Comment by eolivi** [comment]
> maybe make install means also copying all dylibs?

yes, I copy all the files at the install step.

> I am fine releasing without vtk on mac and tell people to use brew with vtk option to have openmeeg with vtk on mac 

good !

for CGAL it has very few libs, it is more template based.

**Comment by agramfort** [comment]
+1 for MRG when CIs are happy

**Comment by agramfort** [comment]
thx @eolivi 

let me know what binaries to test on mac or linux

**Comment by eolivi** [comment]
Yes, Have a look to the binaries. For Mac the package containing all libs is called "-AllLibs-" (maybe "-standalone-" would be better ?? ).
For Windows, I think it is okay, but suddenly my VirtualBox does not work anymore today (fedora upadtes...) I need Theo @papadop  for sudo.

**Comment by agramfort** [comment]
I don't think any of the mac binaries work on mac without brew.

OpenMEEG-2.3.99.0-MacOSX-Intel-OpenBLAS

needs matio and hdf5 from brew.

and

OpenMEEG-2.3.99.0-MacOSX-Intel-OpenBLAS-AllLibs-OpenMP-cgal

needs llvm from brew for openmp reason.

+1 for standalone naming.

**Comment by eolivi** [comment]
ok so I 've re-done all of them standalone, and no openmp nor vtk (nor python)

**Comment by agramfort** [comment]
ok I could test on a mac without brew installed. What I had to do to install was:

Add these libraries to lib:

libgcc_s.1.dylib
libgfortran.4.dylib
libquadmath.0.dylib

Add this symlink:
libsz.2.dylib -> libsz.2.0.0.dylib

@eolivi any idea how to fix this? thx

**Comment by eolivi** [comment]
ok, I can fix that I think.
libgcc_s.1.dylib
libgfortran.4.dylib
libquadmath.0.dylib

these are from openblas.

**Comment by agramfort** [comment]
yes it's for openblas

do you see a way to test our generated binaries with travis?

maybe we could uninstall brew after making the package then expand the
tar.gz and test that om_assemble runs? so we would guarantee we never break
it. I think this should work

**Comment by eolivi** [comment]
wow !!  smart 
yes, It could be great !

**Comment by eolivi** [comment]
for ex. latest windows package is broken I don't know why (others were ok).
I had no VM working, but they just solved the fedora problem now

**Comment by agramfort** [comment]
>
> wow !! smart


:)

when we have a solid packaging / deployment system we can do science again
:)

**Comment by eolivi** [comment]
regarding these libs:
libgcc_s.1.dylib
libgfortran.4.dylib
libquadmath.0.dylib

these are used by  openblas but provided by gcc:
`otool -l /usr/local/Cellar/openblas/0.2.19_1/lib/libopenblas.dylib`

> ...
         name /usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 5.0.0
compatibility version 5.0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1197.1.1
compatibility version 1.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name /usr/local/opt/gcc/lib/gcc/7/libquadmath.0.dylib (offset 24)


as we're not exporting gcc, it is not exported.
I do not see a proper way to do it.

**Comment by agramfort** [comment]
maybe the solution is actually to use the static openblas library

I have libopenblasp-r0.2.19.a on my mac with brew.

**Comment by eolivi** [comment]
doesnot work already tried.... looks broken

**Comment by eolivi** [comment]
is gcc a too heavy dep ?
(I know we call that standalone... but .... )

**Comment by agramfort** [comment]
we cannot ask people to install gcc with brew. It is not an option.

other option is to use apple veclib but is it still much slower?

**Comment by eolivi** [comment]
so I'll try a hack to copy the gcc libs...

**Comment by eolivi** [comment]
why don't we package Bundle instead of TGZ ? !
because there are solutions in this case: fixup_bundle()

https://cmake.org/Wiki/BundleUtilitiesExample

https://www.mail-archive.com/cmake@cmake.org/msg34045.html

https://stackoverflow.com/questions/26043356/do-multiple-gcc-versions-confuse-dylibs-libgcc-s-1-dylib-and-prevent-binaries#26939055

**Pull request merged**
