### PR TITLE
for Mac: install vtk libs as well

### PR DESCRIPTION
**Pull request by eolivi**

### CODE REVIEW

**Comment by agramfort** [comment]
it does not work on travis for now

**Comment by eolivi** [comment]
green.
BTW when you will do the formula with brew, with eventually the options 'vtk', 'omp', 'cgal', ...
It will generate a package ? If yes, vtk libs will be copied too, which is not what the user want.
I could add an option: MAC_COPY_ALL_LIBS (instead of our previous BUILD_STATIC). If ON, this would allow us to deliver packages with all extern libs (vtk,...). If OFF, we will only ship the OpenMEEG ones (for the brew formula for ex).
what do you think ?

**Comment by agramfort** [comment]
Thx !

**Comment by eolivi** [comment]
@agramfort  did you read above ?

**Comment by agramfort** [comment]
yes @eolivi 

we'll need to update the brew formulas I agree.

this is probably the only easy way to have openmp working on mac easily for our mac users

**Comment by agramfort** [comment]
still does not work:

```
$ ./bin/om_assemble
dyld: Library not loaded: /usr/local/opt/vtk/lib/libvtkDomainsChemistryOpenGL2-7.1.1.dylib
  Referenced from: /Users/alex/Downloads/OpenMEEG-2.3.99.0-MacOSX-Intel-OpenBLAS-shared-vtk-cgal/./bin/om_assemble
  Reason: image not found
Abort trap: 6

$ ls lib/
libCGAL.12.0.0.dylib          libboost_atomic-mt.dylib     libhdf5.101.dylib                  libvtkCommonExecutionModel-7.1.1.dylib  libvtkIOXML-7.1.1.dylib
libOpenMEEG.1.1.0.dylib       libboost_chrono-mt.dylib     libmatio.4.dylib                   libvtkCommonMath-7.1.1.dylib            libvtkIOXMLParser-7.1.1.dylib
libOpenMEEG.1.dylib           libboost_date_time-mt.dylib  libmpfr.4.dylib                    libvtkCommonMisc-7.1.1.dylib            libvtksys-7.1.1.dylib
libOpenMEEG.dylib             libboost_system-mt.dylib     libopenblasp-r0.2.19.dylib         libvtkCommonSystem-7.1.1.dylib          libz.1.dylib
libOpenMEEGMaths.1.1.0.dylib  libboost_thread-mt.dylib     libsz.2.0.0.dylib                  libvtkCommonTransforms-7.1.1.dylib      libz.dylib
libOpenMEEGMaths.1.dylib      libexpat.dylib               libvtkCommonCore-7.1.1.dylib       libvtkIOCore-7.1.1.dylib
libOpenMEEGMaths.dylib        libgmp.10.dylib              libvtkCommonDataModel-7.1.1.dylib  libvtkIOLegacy-7.1.1.dylib
```

**Comment by agramfort** [comment]
but these binaries work on my mac:

OpenMEEG-2.3.99.0-MacOSX-Intel-OpenBLAS-shared.tar.gz

it would need to be tested on a mac without brew packages installed

**Pull request merged**
