### PR TITLE
when building static: link against static libs if you can for OpenMEE…

### PR DESCRIPTION
**Pull request by eolivi**
…GMaths.

### CODE REVIEW

**Comment by papadop** [comment]
OK for me except the removal of the white line in AsciiIO.H ;-)

**Comment by eolivi** [comment]
this will be ok for MAC but does not work on linux (anyway... not needed)

**Comment by agramfort** [comment]
can I test the produced binaries if they work?

**Comment by eolivi** [comment]
yes you can. it should be ok now.
I did on our MAC from ci:
ciosx:bin ci$ otool -l om_assemble  | grep -i hdf
ciosx:bin ci$ otool -l om_assemble  | grep -i mat

and no output (and it used to (with the shared matio and hdf5)).

**Comment by agramfort** [comment]
it is not uploaded to http://openmeeg.gforge.inria.fr/download/?C=M;O=D ?

**Comment by eolivi** [comment]
no it will upload only from the master....
so you have to test from my branch called static2

**Comment by agramfort** [comment]
we should be able to upload an openblas version static from travis right?

**Comment by agramfort** [comment]
I am merging so I can test the mac binaries

**Comment by agramfort** [comment]
@eolivi I downloaded http://openmeeg.gforge.inria.fr/download/OpenMEEG-2.3.0.2-MacOSX-Intel-OpenBLAS-static-vtk.tar.gz and it works on my machine but I needs openblas

```
$ ldd om_assemble 
om_assemble:
	/usr/local/opt/openblas/lib/libopenblasp-r0.2.19.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	libOpenMEEGMaths.1.dylib (compatibility version 1.0.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```

it should be possible to use libopenblas.a cf.

$ ls /usr/local/opt/openblas/lib/libopenblas.a 
/usr/local/opt/openblas/lib/libopenblas.a

also this was built by ci.inria.fr or travis? if ci.inria.fr I thought we were using it to use MKL Inria license?

**Comment by eolivi** [comment]
done in https://github.com/openmeeg/openmeeg/pull/198

**Pull request merged**
