### PR TITLE
DOC: Document local builds [ci skip]

### PR DESCRIPTION
**Pull request by larsoner**
@papadop this is how I've debugged on each OS

### CODE REVIEW

**Comment by larsoner** [comment]
The diff is annoying, here is a readable view:

https://github.com/openmeeg/openmeeg/blob/9ebffd7374250234c45970e8487e98120544d2ed/README.rst#build-openmeeg-from-source

**Comment by larsoner** [comment]
... FYI as far as MSVC licenses go, you should be able to use the Community edition.

Also one option would be to start with the dev virtualbox images they provide that come with a fully functional OS + MSVC, but they're only valid for a month I think:

https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/

**Review by agramfort — APPROVED** [review]
❤️

**Comment by papadop** [comment]
But for me the configuration still fails with the following message which seems to indicate VS 2017 whereas I really have VS 2019 installed.
```

$ /y/src/Git/OpenMEEG/openmeeg/build_tools/cmake_configure.sh  /y/src/Git/OpenMEEG/openmeeg
+ cmake -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DPython3_EXECUTABLE=/usr/bin/python -DCMAKE_GENERATOR_TOOLSET=v141 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_SHARED_LINKER_FLAGS= -DCMAKE_MODULE_LINKER_FLAGS= -DCMAKE_PREFIX_PATH= -DCMAKE_TOOLCHAIN_FILE=/y/src/Git/OpenMEEG/openmeeg/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_CXX_FLAGS= -DTEST_HEAD3=ON /y/src/Git/OpenMEEG/openmeeg
-- Building for: Visual Studio 16 2019
-- Bootstrapping vcpkg before install
-- Bootstrapping vcpkg before install - failed
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:858 (message):
  vcpkg install failed.  See logs for more information:
  Y:\compiles\OpenMEEG\OM-windows\build\vcpkg-bootstrap.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:2 (project)


CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 9/6/2022 1:09:52 PM.
    Project "Y:\compiles\OpenMEEG\OM-windows\build\CMakeFiles\3.17.3\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [Y:\compiles\OpenMEEG\OM-windows\build\CMakeFiles\3.17.3\VCTargetsPath.vcxproj]
    Done Building Project "Y:\compiles\OpenMEEG\OM-windows\build\CMakeFiles\3.17.3\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "Y:\compiles\OpenMEEG\OM-windows\build\CMakeFiles\3.17.3\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for Visual Studio 2017 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools, please install Visual Studio 2017 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [Y:\compiles\OpenMEEG\OM-windows\build\CMakeFiles\3.17.3\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

```

**Comment by papadop** [comment]
And the log says:

```
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2022-05-05/vcpkg.exe -> Y:\src\Git\OpenMEEG\openmeeg\vcpkg\vcpkg.exe...While calling Windows API function WriteFile got error 0x00000005:
Access is denied.
```

**Comment by larsoner** [comment]
> I followed your instructions, except that my build directory is separated in another place.

To start, can you try not doing it this way? Following the instructions as closely to verbatim as possible (e.g., letting it make the "build" directory in the source root) should make it more likely to succeed because it's how those instructions were tested/created. Then once it works following exactly we can (if really necessary) relax/change the infrastructure. But deviating from the instructions will increase the likelihood of failure.

(To me it looks like a file permissions problem, possibly because the source root or build directory are not writeable, or maybe the directory above the build directory needs to be writeable or something. But again let's get it working first without modifying the basic setup.)

**Comment by larsoner** [comment]
@papadop okay to merge this one as-is for now? I think we can iterate with follow-up PRs as we go and simplify things with ideas you have in #586

**Pull request merged**
