### PR TITLE
attempt on standalone packages

### PR DESCRIPTION
**Pull request by eolivi**

### CODE REVIEW

**Comment by eolivi** [comment]
@agramfort 
can you please tell me where are these libraries on mac ? (mac from ci still not back online...).

all the libs from ldd/otool of libopenblas


/usr/local/lib/libopenblas.dylib openblas  

lapacke  

quadmath  

gcc_s  

gfortran  

gomp ?

**Comment by agramfort** [comment]
see https://github.com/openmeeg/openmeeg/pull/211

What I add to do to make it work a fresh mac was copy:

libgcc_s.1.dylib
libgfortran.4.dylib
libquadmath.0.dylib

Add this symlink:
libsz.2.dylib -> libsz.2.0.0.dylib

but honestly for me the mac binaries work as they are. They use vecLib and
no openmp but at least it works.

what do you think?

**Comment by eolivi** [comment]
I think it is good now for both Mac and linux with openblas. let.s merge and try ?

-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblas.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/share/OpenMEEG/cmake/OpenMEEGDependencies.cmake
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/share/OpenMEEG/cmake/Findmatio.cmake
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/share/OpenMEEG/cmake/FindOpenBLAS.cmake
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblasp-r0.2.19.dylib
-- Up-to-date: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblas.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libquadmath.0.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libquadmath.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libSystem.B.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libpthread.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgfortran.3.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgfortran.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgomp.1.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgomp.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libmatio.4.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libmatio.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libhdf5.101.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libhdf5.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libsz.2.0.0.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libsz.dylib

**Comment by agramfort** [comment]
I had issues is you ship libSystem.B.dylib. Did you change this?

**Comment by eolivi** [comment]
yes I changed the way apple package was done to homogenize with the way linux do. 
- besides libSystem.B.dylib is there any other problem ? 
- BTW libSystem.B.dylib was included because libpthread.dylib points to it right ? (if I remove both system.B and libpthread is it ok ? )

**Comment by eolivi** [comment]
now we do not link with matio.a, hdf5.a ,etc.... because these are not available on linux. So we instead copy these libs in dynamic.

**Comment by agramfort** [comment]
ok. Shall we push to master to have the binaries we can test?

**Comment by eolivi** [comment]
yes either that, or you pull and then build the package locally... as u want

**Comment by agramfort** [comment]
let's use travis. I will be a more reliable conclusion.

**Comment by agramfort** [comment]
I get this error on a fresh mac:

/usr/local/opt/szip/lib/libsz.2.dylib
 Referenced from:
/Users/dengemann/Downloads/OpenMEEG-2.3.99.0-MacOSX-OpenBLAS-standalone-vtk-cgal/./bin/om_assemble
 Reason: image not found

why is this not captured by travis? don't we remove brew from the system to
test at the end?

**Comment by agramfort** [comment]
here is the error on linux:

gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-standalone-OpenMP-vtk$
export LD_LIBRARY_PATH=${PWD}/lib:$LD_LIBRARY_PATH
gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-standalone-OpenMP-vtk$ ls
bin  include  lib  share
gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-standalone-OpenMP-vtk$
chmod +x bin/om_*
gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-standalone-OpenMP-vtk$
./bin/om_assemble
./bin/om_assemble: error while loading shared libraries:
liblapacke.so.3: cannot open shared object file: No such file or
directory

the lib folder does not contain liblapacke.so.3 but only:

gramfort@lame22:OpenMEEG-2.3.99.0-Linux-OpenBLAS-standalone-OpenMP-vtk$
ls lib/liblapacke.so*
lib/liblapacke.so  lib/liblapacke.so.3.0

**Pull request merged**
