### PR TITLE
fixing #314 using the same mechanism as https://github.com/CBICA/CaPTk/pull/490

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixing https://github.com/openmeeg/openmeeg/issues/314

### CODE REVIEW

**Comment by agramfort** [comment]
@massich what do you think. At least CIs are happy

**Comment by massich** [comment]
If that's the solution (as it seems to be) and the artifact binaries work
I'm +1. We should even remove the lines rather than comment them.

@cbica, can you show a braking case and how this pr fixes it? Thx

**Comment by papadop** [comment]
And the comment above those lines or at least the part that is obsolete....

**Comment by sarthakpati** [comment]
I can remove that comment (I kept it for consistency for you folks to begin with). So far, we haven't seen any breaking cases for this.

**Comment by sarthakpati** [comment]
Turns out, that code was already there. I just removed the hard-coded path in the root CMakeLists file and uncommented that call.

**Comment by agramfort** [comment]
Thx @sarthakpati

**Comment by massich** [comment]
@sarthakpati <https://github.com/sarthakpati> Thx!!

**Comment by sarthakpati** [comment]
You're welcome

**Pull request merged**
