### PR TITLE
Solving bug on parsing int-labeled sensors.

### PR DESCRIPTION
**Pull request by eolivi**

### CODE REVIEW

**Comment by eolivi** [comment]
I've tried to solve the bug on sensor as discussed there https://github.com/openmeeg/openmeeg/pull/354
It works on my machine :-) but fail I don't know why on travis...
I'm sorry I don't have much time to look at it.
feel free to close this PR

**Comment by agramfort** [comment]
@eolivi can you rebase this branch on master? CIs are fixed

**Comment by massich** [comment]
The segfaults are legit
https://travis-ci.org/openmeeg/openmeeg/jobs/511926137#L1598

**Comment by eolivi** [comment]
I add to correct since '0' can be a valid float... 
anyway, as papadop said, we should re-do all of this...

**Comment by massich** [comment]
@eolivi Thx for the fix!!! :+1: 

Could you please add a regression test at the same time to make sure that we cover this (and the new code)? 

Thx

**Pull request merged**
