### PR TITLE
[WIP] Openblas support

### PR DESCRIPTION
**Pull request by agramfort**
taking over #121

### CODE REVIEW

**Comment by agramfort** [comment]
@eolivi I rebased your branch and added support for mac.

it seems to work on my mac but @papadop I still have the heisenbug with OpenMEEGMathsTest-full

I'm testing now on travis for mac

**Comment by agramfort** [comment]
oh yeah openblas is working on mac and linux !

ready to merge on my end

cc @papadop @eolivi

**Comment by eolivi** [comment]
hi @agramfort ,
It is really a shame that Theo @papadop  did not finish his branch https://github.com/papadop/openmeeg/tree/UniLapack , because it is much better done there. (I've found his branch after making this PR..).
The thing is, I think it has a problem of c++ include with extern keyword, but Theo should tell us what is the problem, and how bad this PR is compared to his...

**Comment by agramfort** [comment]
@papadop is welcome to open a PR but are you ok to merge this?

to me it's working.

as I say (and have been told)

make it work
make it nice
make it fast

I made it work.
I'll let @papadop make it nice when he has time.

ok?

**Comment by eolivi** [comment]
then ok !

**Pull request merged**
