### PR TITLE
MAINT: Use std::filesystem

### LINKED ISSUE #542: Use std::filesystem
And remove OpenMEEG/include/filenames.h
It should be available on all compiler with C++-17 support

### PR DESCRIPTION
**Pull request by larsoner**
Let's see if this works

Closes #542

### CODE REVIEW

**Comment by papadop** [comment]
I thought it was a lost cause for now at least because of lack of implementation in old versions of the compilers.....

**Comment by larsoner** [comment]
`cibuildwheel` can handle it, which I think is as far back as we should reasonably need to support. The compilers there should have proper C++17 support. I'm hoping for macOS I "just" need to set the version min to 10.15...

**Comment by larsoner** [comment]
This is all good with minor modifications to #543, @papadop feel free to merge if you're happy!

**Comment by larsoner** [comment]
From a quick look with @agramfort this was good to go!

**Pull request merged**
