### PR TITLE
Add missing exception for block API.

### PR DESCRIPTION
**Pull request by papadop**
Un-revert the Block API (commit 1). This one should not be problematic as it just adds new classes.

### CODE REVIEW

**Comment by larsoner** [comment]
MSVC/windows failures are real

https://github.com/openmeeg/openmeeg/runs/7579069788?check_suite_focus=true

**Comment by larsoner** [comment]
@papadop can you please revert? I think it's critical we keep CIs green, and they were red here

**Comment by agramfort** [comment]
@papadop did you just merge a red PR consciously ?

**Comment by papadop** [comment]
I do not understand. All tests were green after the third commit....  Are you sure you updated the github page ?
Windows build were indeed failing before the last commit but all passed after it...

I have some troubles because I do no longer receive the notifications on the issues or the cis. I have not changed anything and the github configuration says that I should receive them. Any idea ? I still receive the merge and commit notifications.
This is why I did not see the last messages posted here and send the emails....

**Comment by papadop** [comment]
And the issue was actually closed. Resent as PR #498. Let's see what testers will say.

**Comment by papadop** [comment]
And no I will not 'merge a red PR consciously ?'.
I appreciate enough the fact that they work again (and thanks again).

**Comment by larsoner** [comment]
@papadop it shows up as red above, even now:

Screenshot from 2022-07-29 16-07-10


But I think this is just a GitHub issue since looking at the actual statuses, everything is green (or neutral/not run). So I think we're actually okay here!

**Pull request merged**
