### PR TITLE
MNT: Fixes for conda-forge

### PR DESCRIPTION
**Pull request by larsoner**
Attempt to fix conda-forge in https://github.com/conda-forge/openmeeg-feedstock/pull/18

### CODE REVIEW

**Comment by larsoner** [comment]
@agramfort can you give me access to https://ci.appveyor.com/project/openmeegci/openmeeg so I can restart CIs when needed?

**Comment by agramfort** [comment]
I don't know how to do this :(

switching to GH actions on windows will be necessary anyway and the CI is
way more reactive

**Comment by larsoner** [comment]
@agramfort ready for review/merge from my end. My plan is:

## Phase 1

Get up-to-date packages on conda-forge for Linux and macOS:

1. Merge this
2. Cut 2.4.2 release
3. Use this release in https://github.com/conda-forge/openmeeg-feedstock/pull/18 and merge if it's green

## Phase 2

Get Windows working (again?) on conda-forge:

1. Reenable Windows on CI here by following SciPy's OpenBLAS build instructions
2. Fix any windows-specific bugs (I think I found one in https://github.com/conda-forge/openmeeg-feedstock/pull/18)
3. Reenable Windows on conda-forge

## Phase 3

Get PyPi wheels working by following whatever NumPy/SciPy does to release wheels with OpenBLAS.

Somewhere along the way I might need to add a proper `setup.py` or so, we'll see.

**Review by agramfort — APPROVED** [review]
❤️

**Pull request merged**
