### PR TITLE
remove useless adresses

### PR DESCRIPTION
**Pull request by eolivi**

### CODE REVIEW

**Comment by agramfort** [comment]
Please revert

These addresses are in the git tree and now git shortlog will not work. It's too late. These emails are in the commits

**Comment by agramfort** [comment]
before this commit:

```
git shortlog -s
   347  Alexandre Gramfort
     1  Boris Burle
     2  Dang Kai
     2  Daniel Miklody
   559  Emmanuel Olivi
     2  Kyle Beauchamp
     1  Marmaduke Woodman
    74  Maureen Clerc
    12  Perrine Landreau
     5  Renaud Keriven
     1  Sylvain Vallaghe
   707  Theodore Papadopoulo
     2  Thierry Guillemot
     4  Yaroslav Halchenko
     1  lazyparser
```

after this commit:

```
   347  Alexandre Gramfort
     1  Boris Burle
     2  Dang Kai
     2  Daniel Miklody
   409  Emmanuel Olivi
     2  Kyle Beauchamp
     1  Marmaduke Woodman
    74  Maureen Clerc
    12  Perrine Landreau
     5  Renaud Keriven
     1  Sylvain Vallaghe
   707  Theodore Papadopoulo
     2  Thierry Guillemot
     4  Yaroslav Halchenko
   150  eolivi
     1  lazyparser
     2  manolivi
```

i am reverting now.

**Comment by eolivi** [comment]
ok ....
 

> These addresses are in the git tree and now git shortlog will not work. It's too late. These emails are in the commits

rrrrr, may I rewrite history ? there must be a way !

**Comment by eolivi** [comment]
https://help.github.com/articles/changing-author-info/ 

can I ??

**Comment by eolivi** [comment]
maybe too dangerous/annoying ....

Note: Running this script rewrites history for all repository collaborators. After completing these steps, any person with forks or clones must fetch the rewritten history and rebase any local changes into the rewritten history.

**Comment by agramfort** [comment]
no it's too late. You will break the clone of too many people. I don't see
your problem. These emails are already on every PR, clone etc.

**Pull request merged**
