### PR TITLE
adding tag 2.4.prerelease (and package version 2.3.99)

### PR DESCRIPTION
**Pull request by eolivi**

### CODE REVIEW

**Comment by eolivi** [comment]
is it ok for you to specify 2.3.99 as a pre-release version ?
seen there: https://cmake.org/pipermail/cmake/2009-May/029450.html

**Comment by agramfort** [comment]
what @maedoc means is to do something like

git tag v2.3.2
git push --tags

**Comment by eolivi** [comment]
yes I know, I can do that once the version as changed internally (= this PR accepted)

**Comment by agramfort** [comment]
ok for me

**Pull request merged**
