### PR TITLE
Docstrings

### PR DESCRIPTION
**Pull request by papadop**
A small changes to re-enable docstrings in the python module...

### CODE REVIEW

**Comment by papadop** [comment]
PS: I leave the work of adding a travis/appveyor config that checks that documentation is built.
I can do this but I'm unsure to which build you prefer to add it.
Obviously, with the current checker, the only important modification (in openmeeg.i) of this PR is not tested....

**Comment by papadop** [comment]
Is travis build with python2 or python3 (to understand why the docstring.i file has not been generated).

**Comment by papadop** [comment]
OK it is probably related to a parallel build and a missing dependency. I pushed a temptative fix.

**Comment by massich** [comment]
Everything is build in python 3.

Python 2 is no longer supported on 2020

**Comment by massich** [comment]
We still build it in openmeeg-feedstock until then, though

**Pull request merged**
