### PR TITLE
[WIP] Activate clang static analysis

### PR DESCRIPTION
**Pull request by massich**

### CODE REVIEW

**Comment by agramfort** [comment]
@massich can you activate analyse ON on linux too so @papadop can see the errors it reports and eventually look into it?

**Comment by massich** [comment]
I'm not sure about the usefulness of static analyzing during the generation of the building system. If we have it active, it complains about the `cpp` code that we use to test compiler functionalities. 
As example it complains that `res` is never used here: 
```cpp
int main() {
    double d = 3.0;
    const bool res = S::isnormal(d);
    return 0;
}
```

xx

**Comment by massich** [comment]
The rest of the errors should be legid. @papadop are you taking over?

**Comment by agramfort** [comment]
travis is green so no error?

**Comment by massich** [comment]
There are plenty warnings. But no error. We can get it in, as it is and then improve the code when we start removing warnings.

I'll merge

**Pull request merged**
