### PR TITLE
start GH config

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
@papadop @eolivi I replicate with github actions https://github.com/openmeeg/openmeeg/pull/416/checks?check_run_id=598176331 the pb with libmatio hdf5 although I take packaged version from brew. A bug in matio that is not properly tested ?

**Comment by agramfort** [comment]
as you can see @papadop I am going crazy because libmatio now uses a more recent of hdf5 on brew and matio is not properly tested (or we don't use it properly) so our mac os build is again broken...

**Comment by agramfort** [comment]
@papadop if you can push here a build on ubuntu that uses the MKL package that would be very helpful. thanks

**Comment by larsoner** [comment]
I am inclined to close this and start from scratch @agramfort

**Comment by larsoner** [comment]
I am inclined to close this and start from scratch @agramfort

**Comment by agramfort** [comment]
fair enough

**Pull request closed without merging**
