### PR TITLE
Standalone

### PR DESCRIPTION
**Pull request by eolivi**

### CODE REVIEW

**Comment by agramfort** [comment]
tell me what I can do to help

**Comment by eolivi** [comment]
it now looks better:
for linux:
`-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblas.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/liblapacke.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/share/OpenMEEG/cmake/OpenMEEGDependencies.cmake
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/share/OpenMEEG/cmake/Findmatio.cmake
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/share/OpenMEEG/cmake/FindOpenBLAS.cmake
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblas.so.0
-- Up-to-date: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblas.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/liblapacke.so.3.0
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/liblapacke.so.3
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/liblapacke.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libquadmath.so.0.0.0
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libquadmath.so.0
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libquadmath.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgcc_s.so.1
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgcc_s.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libpthread.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgfortran.so.3.0.0
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgfortran.so.3
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgfortran.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgomp.so.1.0.0
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgomp.so.1
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgomp.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libmatio.so.2.0.2
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libmatio.so.2
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libmatio.so
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libhdf5.so.7.0.0
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libhdf5.so.7
-- Installing: /home/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libhdf5.so`

**Comment by eolivi** [comment]
for Mac: 
maybe it should be libopenblas.19.dylib instead of libopenblas.dylib.19 ? is it important ? can we try ?

> -- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblasp-r0.2.19.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblas.dylib.19
-- Up-to-date: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libopenblas.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libquadmath.0.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libquadmath.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgfortran.3.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgfortran.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgomp.1.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libgomp.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libmatio.4.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libmatio.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libhdf5.101.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libhdf5.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libsz.2.0.0.dylib
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libsz.dylib.0
-- Installing: /Users/travis/build/openmeeg/openmeeg/build/OpenMEEG/install/lib/libsz.dylib

**Comment by agramfort** [comment]
ok let's try ! thx @eolivi for all your efforts

**Comment by eolivi** [comment]
is it okay for MAC ?
for linux I don't know why but it seems it needs /usr/bin/lapack.so and blas.so even if we provided libopenblas and liblapacke . it looks like liblapacke is linked to blas and lapack.  
I see 3 choices Either:
- I copy too the liblapack.so and libblas.so ?
- or we investigate on the why lapacke needs lapack and blas
- or I give up this standalone, and we ship openmeeg with our own clapack, matio and hdf5 (so that nothing else is required to be copied).

what do you think on that please @papadop and @agramfort  ?

**Comment by agramfort** [comment]
>
> is it okay for MAC ?
>

no :(

$ DYLD_LIBRARY_PATH=$PWD/lib bin/om_forward
dyld: Library not loaded: /usr/local/opt/szip/lib/libsz.2.dylib
  Referenced from:
/Users/larsoner/Downloads/OpenMEEG-2.3.99.0-MacOSX-OpenBLAS-standalone-vtk-cgal/bin/om_forward
  Reason: image not found
Abort trap: 6

you should really remove brew completely from the system to test the
packaged binaries.


> for linux I don't know why but it seems it needs /usr/bin/lapack.so and
> blas.so even if we provided libopenblas and liblapacke . it looks like
> liblapacke is linked to blas and lapack.
>

can you remove blas and lapack from the system to make sure it is not
used/necessary for our binaries?

> I see 3 choices Either:
>
>    - I copy too the liblapack.so and libblas.so ?
>    - or we investigate on the why lapacke needs lapack and blas
>
> +1

>
>    - or I give up this standalone, and we ship openmeeg with our own
>    clapack, matio and hdf5 (so that nothing else is required to be copied).
>
>
did you do a benchmark with clapack? how much slower is it?

**Comment by eolivi** [comment]
> you should really remove brew completely from the system to test the packaged binaries.

no. because we need it after to upload the package (python, conda, paramiko, pip, ...)

> did you do a benchmark with clapack? how much slower is it?

no, not this one. I'm doing it ...

**Comment by agramfort** [comment]
On Thu, Jul 20, 2017 at 11:41 AM, eolivi <notifications@github.com> wrote:

> you should really remove brew completely from the system to test the
> packaged binaries.
>
> no. because we need it after to upload the package (python, conda,
> paramiko, pip, ...)
>
for me only need conda to upload not brew. Python does not come from brew.

> did you do a benchmark with clapack? how much slower is it?
>
> no, not this one. I'm doing it ...
>
thx

**Pull request merged**
