### PR TITLE
attempt to setup deployment to gforge of packages

### PR DESCRIPTION
**Pull request by agramfort**

### CODE REVIEW

**Comment by agramfort** [comment]
@papadop @eolivi now the binaries for linux and mac are uploader automatically on gforge:

see

http://openmeeg.gforge.inria.fr/download/OpenMEEG-2.3.0.1-Ubuntu_14.04-x86_64-static.tar.gz
http://openmeeg.gforge.inria.fr/download/OpenMEEG-2.3.0.1-MacOSX-Intel-static.tar.gz

in http://openmeeg.gforge.inria.fr/download/

PR is good to go on my end.

what you will see if that the static build is broken :( :( It says static in file name but if you look inside all the libraries are .so and the link is dynamic even with system libraries.

@papadop time to fix this?

**Comment by agramfort** [comment]
@papadop @eolivi can I merge?

**Comment by eolivi** [comment]
It is a nice improvement... ok for me !

**Comment by agramfort** [comment]
Cool merging.

**Pull request merged**
