### PR TITLE
add lgtm yml file

### PR DESCRIPTION
**Pull request by agramfort**
just a try...

### CODE REVIEW

**Comment by papadop** [comment]
Can you explain what is this ??

**Comment by agramfort** [comment]
code analysis service

>

**Comment by agramfort** [comment]
@papadop for now it thinks it's a python project :( not sure how to fix it...

**Comment by massich** [comment]
The exlude is not working. It is like its only picking up whatever is set in exclude
([see this](https://lgtm.com/projects/g/openmeeg/openmeeg/latest/files/wrapping/src/?sort=name&dir=ASC&mode=heatmap&showExcluded=false) and toggle `show exclude files`)

**Comment by massich** [comment]
in matio lgtm theres a place to click to add languages:
https://lgtm.com/projects/g/tbeu/matio/overview/
so does mne-python
https://lgtm.com/projects/g/mne-tools/mne-python/overview/

**Comment by massich** [comment]
found something that seems useful. https://discuss.lgtm.com/t/c-extraction-problem/1679

**Comment by samlanning** [comment]
As discussed on the [LGTM forum](https://discuss.lgtm.com/t/c-extraction-problem-possibly-due-to-cmake-missing-variable/1961), the `.lgtm.yml` file in 911e1de has been tested and works, so it should be safe to add that to your `master` branch.

**Comment by agramfort** [comment]
thx a lot @samlanning

**Comment by agramfort** [comment]
This pull request **fixes 6 alerts** when merging 10def267fe72a1ecbd79f4310fe31f337484f8d3 into bb186307167986fba6cc8a7af844572d51841126 - [view on LGTM.com](https://lgtm.com/projects/g/openmeeg/openmeeg/rev/pr-d43aed4557b43659fb3f0e2bc9ae46ff22db4239)

**fixed alerts:**

* 4 for Constant return type on member
* 2 for Missing header guard

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by massich** [comment]
Thx a lot @samlanning @agramfort

**Pull request merged**
