### PR TITLE
Multiple nonconductive

### PR DESCRIPTION
**Pull request by papadop**
First to gather comments.

### CODE REVIEW

**Comment by papadop** [comment]
Where are we on this front ? Can we merge ?

**Comment by dang-kai** [comment]
The code and tests are finished. But the analytical solution to compare with is not ready yet. I think we can merge once the analytical solution is added.

**Comment by agramfort** [comment]
what's up with this branch?

**Comment by dang-kai** [comment]
I think we can remove this branch since all the commits have been moved to the "handle zero conductivity" branch and merged.

**Comment by papadop** [comment]
Closed....

**Pull request closed without merging**
