### PR TITLE
[MRG] Fix missing zlib in windows

### PR DESCRIPTION
**Pull request by massich**
Do not look at this.

### CODE REVIEW

**Comment by massich** [comment]
All the trouble seems to be coming from here:
https://github.com/openmeeg/openmeeg/blob/master/OpenMEEGMaths/include/MatlabIO.H#L322

**Comment by agramfort** [comment]
see
https://github.com/openmeeg/openmeeg/blob/master/cmake/Findmatio.cmake#L25
that I had to do on mac to make sure libz static is used.

**Comment by massich** [comment]
@openmeeg/owners this is good on my end. **Squash and merge** when ready.

**Comment by massich** [comment]
Does the ping to owners work?
cc: @agramfort @papadop

**Comment by agramfort** [comment]
Great job @massich

**Pull request merged**
