### PR TITLE
MAINT: Test VTK

### PR DESCRIPTION
**Pull request by larsoner**
Should reenable VTK on Ubuntu builds. If this slows them down much then I'll restrict which CIs it runs on more.

### CODE REVIEW

**Comment by larsoner** [comment]
Okay there are a bunch of real bugs:

<details>
```
-- The imported target "vtkParseOGLExt" references the file
   "/usr/bin/vtkParseOGLExt-7.1"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_[64](https://github.com/openmeeg/openmeeg/runs/7598842544?check_suite_focus=true#step:15:65)-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.
```
</details>

@papadop feel free to push commits if you're interested in looking, otherwise I can debug this week hopefully

**Comment by larsoner** [comment]
@papadop feel free to push commits if you're interested in looking, otherwise I can debug this week hopefully

**Comment by larsoner** [comment]
... to push commits here, you could do for example:

```
git remote add larsoner git@github.com:/larsoner/openmeeg.git
git fetch larsoner
git checkout -b vtk larsoner/vtk  # creates a local branch "vtk" that tracks larsoner/vtk
<hack>
git commit -am 'BUG: Fix VTK bug'
git push
```

**Comment by papadop** [comment]
I tried with a bad idea. vtk packaging seems broken. It creates a /usr/bin/vtk7 directory but the cmake module looks for /usr/bin/vtk. Maybe we can add a symlink to solve that problem ?

**Comment by larsoner** [comment]
We might be able to test using the conda package like we do for MKL. I'll experiment a bit this week

**Comment by larsoner** [comment]
Locally on 22.04 it works fine with `libvtk9-dev` so I'm going to try installing and using it on the one run we currently have that uses 22.04

**Comment by larsoner** [comment]
(but we should still consider removing VTK support if possible I think!)

**Comment by larsoner** [comment]
Okay this seems to be making the 22.04 build take too long. It was already slow because it has to build OpenBLAS from their `develop` branch.

I'll add it to another CI run instead

**Comment by larsoner** [comment]
Okay I see:
```
-- Found VTK, including requested VTK IO support...
```
in https://github.com/openmeeg/openmeeg/runs/7615129586?check_suite_focus=true#step:15:74 and there are way more tests running, so I think it's working.

@papadop feel free to review and marge for "merge when green" if you're happy

**Comment by papadop** [comment]
Thank you very much. Merging. For the removal of the vtk stuff, I need to review what it brings..... Note that we do not use all vtk but just the IOs (I think) so that it's maybe not as difficult as a full fledged vtk project.

**Pull request merged**
