### PR TITLE
MAINT: Restore test on MKL

### LINKED ISSUE #508: BUG: Fix bugs with Python wrappers
Several Python tests are marked with `@pytest.mark.xfail` and `@pytest.mark.skip` in `wrapping/python/openmeeg/tests/*.py`. These should be released and a new minor or patch version released.

- [x] `BAD_TYPE`: https://github.com/openmeeg/openmeeg/pull/529
- [x] `BAD_PYPY`: https://github.com/openmeeg/openmeeg/pull/533, fixed by @papadop in https://github.com/openmeeg/openmeeg/pull/536
- [x] `BAD_MKL`: https://github.com/openmeeg/openmeeg/pull/532
- [x] `BAD_MSVC`: https://github.com/openmeeg/openmeeg/pull/540

### PR DESCRIPTION
**Pull request by larsoner**
Toward #508, let's see what fails if we remove all ~~`BAD_MSVC`~~ `BAD_MKL` skips.

Closes #508

### CODE REVIEW

**Comment by larsoner** [comment]
Replicated on wheel build:

https://github.com/openmeeg/openmeeg/runs/7706542127?check_suite_focus=true#step:4:2357

<details>

```
  ============================= test session starts =============================
  platform win32 -- Python 3.7.9, pytest-7.1.2, pluggy-1.0.0
  rootdir: c:\
  collected 9 items
  
  Users\runneradmin\AppData\Local\Temp\cibw-run-zun2jw_x\cp37-win_amd64\venv-test\lib\site-packages\openmeeg\tests\test_doc.py . [ 11%]
                                                                           [ 11%]
  Users\runneradmin\AppData\Local\Temp\cibw-run-zun2jw_x\cp37-win_amd64\venv-test\lib\site-packages\openmeeg\tests\test_geom_import.py . [ 22%]
                                                                           [ 22%]
  Users\runneradmin\AppData\Local\Temp\cibw-run-zun2jw_x\cp37-win_amd64\venv-test\lib\site-packages\openmeeg\tests\test_make_geometry.py ::endgroup::Testing wheel...
                                                               ✕ 36.98s
  Error: Command bash D:\a\openmeeg\openmeeg/build_tools/cibw_test_command.sh D:\a\openmeeg\openmeeg failed with code 1. None
```

</details>

And in a `build_and_test.yml` run:

https://github.com/openmeeg/openmeeg/runs/7706542896?check_suite_focus=true#step:20:468

<details>

```
============================= test session starts =============================
platform win32 -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
rootdir: C:\
collected 9 items

..\..\Miniconda\envs\test\lib\site-packages\openmeeg\tests\test_doc.py . [ 11%]
                                                                         [ 11%]
..\..\Miniconda\envs\test\lib\site-packages\openmeeg\tests\test_geom_import.py . [ 22%]
                                                                         [ 22%]
..\..\Miniconda\envs\test\lib\site-packages\openmeeg\tests\test_make_geometry.py 
Error: Process completed with exit code 1.
```

</details>

@papadop what do you recommend for debugging here? I could probably get a debug build going on my Windows machine and then run `ctest` with it for example, but I'm wondering if you had suggestions for the best way to debug it.

Is it possible it's just a bug with our paths, e.g., `D:\a\openmeeg\openmeeg/data` should be `D:\a\openmeeg\openmeeg\data`? If so maybe just replaciing `/` with `\` on Windows builds would make things work. (It would be nice to not care about `/` vs `\` on Windows paths, so I see this as a bug fix of sorts.)

Either way, it seems like this code should not just exit with a value of 1, but rather raise an informative Python error (RuntimeError? FileNotFoundError?). So even if we do fix the paths and/or make the path handling better, it seems like there is a problem with proper exception handling here.

**Comment by larsoner** [comment]
> Either way, it seems like this code should not just exit with a value of 1, but rather raise an informative Python error (RuntimeError? FileNotFoundError?). So even if we do fix the paths and/or make the path handling better, it seems like there is a problem with proper exception handling here.

For this part I added a little test -- it looks like we do `raise RuntimeError` already. This should be FileNotFoundError but seems like a pain to change, so we can do that later. When adding this test, though, locally I see:
```
swig/python detected a memory leak of type 'std::map< unsigned int,unsigned int > *', no destructor found.
swig/python detected a memory leak of type 'std::map< unsigned int,unsigned int > *', no destructor found.
swig/python detected a memory leak of type 'std::map< unsigned int,unsigned int > *', no destructor found.
```
So some leak here to potentially fix as well.

**Comment by papadop** [comment]
I have no specific suggestions for debugging. Personally, I find it much more easy for complicated bugs to replicate the bug on a virtual machine. And yes I first run a ctest, and then proceed with a debugger (copying the ctest command line after having done a ctest -V -I xx,xx to replicate the test). But python is even more complicated. I usually end up adding debug messages in the openmeeg.i file as I do not know how to start the debugger for the python modules, this is probably possible with attaching a gdb to an existing process, but I never did that.

**Comment by papadop** [comment]
Note that while having a look at this, I found that the python error messages were not done the way I thought they would be. So  I have a PR to improve slightly on this side.

**Pull request merged**
