### PR TITLE
MAINT: Update license

### LINKED ISSUE #544: MAINT: Define OpenMEEG developers in license
I'd rather not have to keep updating this, can we just say `OpenMEEG developers` or something?

Otherwise, please add my name at least. But to be complete, something like this would get you a list:
```
$ git shortlog -s --group=author --group=trailer:co-authored-by
   388  Alexandre Gramfort
     1  Boris Burle
     2  Dang Kai
     3  Daniel Miklody
   566  Emmanuel Olivi
   114  Eric Larson
     1  J-H-Cho
    48  Joan Massich
     2  Kyle Beauchamp
     1  Marmaduke Woodman
    76  Maureen Clerc
    12  Perrine Landreau
     5  Renaud Keriven
     1  Sarthak Pati
     1  Sylvain Vallaghe
     1  The Gitter Badger
  1020  Theodore Papadopoulo
     2  Thierry Guillemot
     1  Thomas Baag
     4  Yaroslav Halchenko
     1  j-l-s
     1  lazyparser
```
And there are some names in there we'd need to ping people about...

_Originally posted by @larsoner in https://github.com/openmeeg/openmeeg/pull/539#discussion_r945346107_

### PR DESCRIPTION
**Pull request by larsoner**
Closes #544 

1. Update copyright to contain the "authors of OpenMEEG"
2. Add a link to GitHub to see who has contributed. Maybe we should just get rid of the `Contributors:` line entirely...
3. Update the license text to actually contain the up-to-date official text directly copied from https://cecill.info/licences/Licence_CeCILL-B_V1-en.html

### CODE REVIEW

**Review by agramfort — APPROVED** [review]
@papadop merge if happy

**Comment by papadop** [comment]
I'm a little bit annoyed because the git contributor page does not mention several pre-git developers and particularly some of the initial developers such as G. Adde, R. Keriven and J. Kybic.... Some of them appear in git log (R. Keriven and P. Landreau) but not in git contributors page for a reason I do not understand (it was probably commits from the svn era on the gforge). I think we have to work out a proper contributors page. It can be either as a file (or integrated to LICENSE,.txt) or on the web site...

Minor stuff, I changed the full license text for one that is better formatted (i.e. not taken from html which lost several bullets and numbered list and is 80 column compliant). I'm unsure about the expression: 
© Copyright INRIA, ENPC, and authors of OpenMEEG

**Comment by papadop** [comment]
Here is a proposal for a Contributors file or web page. I hope I have not mis-represented anyone.
Feel free to improve/modify/make suggestions.

.. _contributors:

Contributors
------------

Contributors to OpenMEEG
^^^^^^^^^^^^^^^^^^^^^^^^

     - Original contributors:
       Geoffray ADDE, Maureen CLERC, Alexandre GRAMFORT, Renaud KERIVEN, Jan KYBIC,
       Emmanuel OLIVI, Theodore PAPADOPOULO.

     - Build system and code maintenance: Alexandre GRAMFORT,  Yaroslav HALCHENKO,
       Thierry GUILLEMOT, Eric LARSON, Joan MASSICH, Emmanuel OLIVI,
       Theodore PAPADOPOULO, Sarthak PATI.

     - Non-nested geometries: Maureen CLERC, Emmanuel OLIVI, Theodore PAPADOPOULO.

     - Zero-conductivity domains: Maureen CLERC, KAI DANG.

     - Electrical Impedance Tomography: Maureen CLERC, Emmanuel OLIVI, Sylvain VALLAGHE.

     - Python and Matlab Interface: Alexandre GRAMFORT, Kyle BEAUCHAMP, Boris BURLE,
       Emmanuel OLIVI, Theodore PAPADOPOULO, Jean-Luc SPZYRKA.

     - Various bug fixes and improvements: Thomas BAAG, J.H. CHO, Perrine LANDREAU,
       Daniel MIKLODY, Marmaduke WOODMAN.

**Comment by papadop** [comment]
I'm also checking a few things with the local lawyer and Maureen...

**Comment by larsoner** [comment]
Works for me. Want to make a PR to https://github.com/openmeeg/openmeeg.github.io to add this? Then we can build and deploy the docs and update the link here to point to the `contributors` page.

>  I'm unsure about the expression: © Copyright INRIA, ENPC, and authors of OpenMEEG

I would prefer actually just using `© OpenMEEG Developers.` or something even simpler, similar to what's done in NumPy and scikit-learn, I just wasn't sure if I could remove INRIA/ENPC:

https://github.com/numpy/numpy/blob/b6a3e837785eac58a2f68e126f4db7895ca047b3/LICENSE.txt#L1

https://github.com/scikit-learn/scikit-learn/blob/9aae2adf9198172ec2f583db03c046434709c036/COPYING#L3

**Comment by papadop** [comment]
I'm not against it, but I'm almost certain that we cannot change this line like that. That's why I asked the local lawyer.
I'm pretty sure that INRIA and ENPC are the legal entities that hold the copyright and clearly it would be
troublesome to remove them (specifically ENPC which is no longer represented in the dev-team but was heavily
involved in the original code).

Then, can we add other copyright holders like that is what I wanted to check. ??
All the more that if we do that, we also need to make all the file header coherent with it.

**Comment by papadop** [comment]
To advance, my proposal would be to keep the original copyright for now.
I'll commit the contributors page to the openmeeg.github.io site and we refer to it.
Then when we get some feedback from Maureen and/or lawyers (it probably will take a few weeks),
 then we eventually update depending on what they say.

**Comment by papadop** [comment]
But before committing to github.io, it would be great to have a validation by @agramfort just to be sure
that I have not mis-represented some contributors.

**Comment by larsoner** [comment]
Changes LGTM, marking as squash+merge-when-green

**Comment by papadop** [comment]
Ok. I have changed the contributor url to point to the web site.
Feel free to update contributions there.
For the rest, it will wait for the end of the month (after my week of vacation) when I will have some other feedback.
Thanks.

**Pull request merged**
