### PR TITLE
add Gifti automatic support

### PR DESCRIPTION
**Pull request by eolivi**
but not automatically tested on travis since sometimes the sourceforge which download nifti/gifti stalls....

### CODE REVIEW

**Comment by agramfort** [comment]
I am against merging anything that is not tested. If needs be make a minor on github. It must exists already I am sure.

**Comment by eolivi** [comment]
as you want.... it worked on my machine but problems on the old trusty because it is linking -libm and it is not the correct way (I would have to patch again the nifti... )

**Comment by agramfort** [comment]
Honestly I don't really see the point of this PR

We have already a code base too big for the engineering time we have and we keep adding dependencies. We should focus on quality. Cf bug reported on brainstorm forum yesterday with new binaries. FYI I am presently on holidays and we have the deadline for the BACI conf for a stable release.

**Comment by larsoner** [comment]
I too am inclined to support *less* mesh I/O support inside OpenMEEG if possible and let people use mesh conversion routines instead. Okay to close @eolivi ?

**Pull request closed without merging**
