### PR TITLE
Cleancode

### PR DESCRIPTION
**Pull request by eolivi**
and avoid dangling else problem.
cmake desambiguation on CMP0054

### CODE REVIEW

**Comment by papadop** [comment]
It is almost impossible to see where is the important change...

**Comment by agramfort** [comment]
@eolivi avoid cosmetic changes in the middle of real changes as indeed the diffs are not readable easily.

**Comment by agramfort** [comment]
@eolivi are these only cosmetic changes?

if so +1 for MRG

**Comment by eolivi** [comment]
now yes, only cosmetic changes following the established coding_guidelines.txt ;-)

**Comment by agramfort** [comment]
thx @eolivi

**Pull request merged**
