### PR TITLE
brew doctor + config

### PR DESCRIPTION
**Pull request by agramfort**
attempt to fix brew

### CODE REVIEW

**Comment by eolivi** [comment]
HOMEBREW_VERSION: 1.2.2

ORIGIN: https://github.com/Homebrew/brew.git

HEAD: 54e01d76db34a3a649c79b189873bfd0a52dbc9f

Last commit: 3 days ago

Core tap ORIGIN: https://github.com/Homebrew/homebrew-core

Core tap HEAD: 916bb8ea4c4dd781cad49717430b43f30710c5c7

Core tap last commit: 50 minutes ago

HOMEBREW_PREFIX: /usr/local

HOMEBREW_REPOSITORY: /usr/local/Homebrew

HOMEBREW_CELLAR: /usr/local/Cellar

HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com

CPU: dual-core 64-bit nehalem

Homebrew Ruby: 2.0.0-p648

Clang: 7.3 build 703

Git: 2.13.1 => /usr/local/bin/git

Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.1/bin/perl

Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7

Ruby: /Users/travis/.rvm/rubies/ruby-2.0.0-p648/bin/ruby

Java: 1.8.0_92, 1.8.0_74, 1.8.0_60

macOS: 10.11.6-x86_64

Xcode: 7.3.1

CLT: 7.3.1.0.1.1461711523

X11: 2.7.9 => /opt/X11

Your system is ready to brew.

**Comment by eolivi** [comment]
do you want me to copy that info there ?
https://github.com/Homebrew/brew/issues/2742

**Comment by agramfort** [comment]
I just did

I can replicate the error locally after a brew update

it's a matio issue apparently.

```
test 1
    Start 1: OpenMEEGMathsTest-vector

1: Test command:
/Users/alex/work/bin/openmeeg_brew2/libs/OpenMEEGMaths/tests/OpenMEEGMathsTest-vector
1: Test timeout computed to be: 1500
1:
1: ========== vectors ==========
1: v =
1: 0 1 2 3 4 5 6 7
1: v =
1: 0 1 2 3 4 5 6 7
1: MAT :
1: libc++abi.dylib: terminating with uncaught exception of type
OpenMEEG::maths::BadFileOpening: Exception: Unable to open the file
tmp_matrix.mat for writing
1/1 Test #1: OpenMEEGMathsTest-vector .........***Exception: Other  0.01 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.05 sec

The following tests FAILED:
 1 - OpenMEEGMathsTest-vector (OTHER_FAULT)
Errors while running CTest
```

**Comment by eolivi** [comment]
> it's a matio issue apparently.

strange since it seems we stil download the same http://homebrew.bintray.com/bottles-science/libmatio-1.5.10_1.el_capitan.bottle.tar.gz as before...

me I don't know....

**Comment by agramfort** [comment]
@iMichka are  you ready this thread?

**Comment by iMichka** [comment]
@agramfort Now I am reading it. I will have time to look at this closely in the next hours.

**Comment by iMichka** [comment]
Just one note: you could run `make CTEST_OUTPUT_ON_FAILURE=1 test` instead of `make test` to get the test output on stdout in Travis. Never tested that but it should work.

**Comment by iMichka** [comment]
FYI, the only change I did in libmatio is to remove the `--with-hdf5` flag. This means that libmatio is now built with hdf5 support by default. `Pouring libmatio-1.5.10_1.el_capitan.bottle.tar.gz` is great because now you get a precompiled binary, instead of having to rebuild from source. This should reduce your build/test time.

**Comment by iMichka** [comment]
While trying to build openmeeg outside of homebrew, I am getting:
> matio_DIR-NOTFOUND
> vecLib_DIR-NOTFOUND

Both are not find the cmake configuration file. For libmatio; there is no such file. Not sure what vecLib should point to.

**Comment by eolivi** [comment]
errors from travis are like this:

> libc++abi.dylib: terminating with uncaught exception of type OpenMEEG::maths::BadFileOpening: Exception: Unable to open the file /Users/travis/build/openmeeg/openmeeg/OpenMEEG/build/tests/HeadNNb1-tangential.h2mm for writing

I'll try tomorrow to reproduce locally.

regarding your build: did you build the openmeeg directory or the openmeeg/OpenMEEG dir ?
FindvecLib is looking for:
> find_path(vecLib_INCLUDE_DIR vecLib.h
          DOC "vecLib include directory"
          PATHS /System/Library/Frameworks/Accelerate.framework/Versions/Current/${__veclib_include_suffix}
                /System/Library/${__veclib_include_suffix}
                /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Headers/
          NO_DEFAULT_PATH)

**Comment by agramfort** [comment]
@iMichka so let's continue here. Basically with the latest libmatio formula tests don't pass but with this version it works (on my mac):

https://github.com/Homebrew/homebrew-science/blob/c2042d3f910bffe1311fe7ce23992cd91a13eed7/libmatio.rb

in other words the precompiled binaries now shipped with current brew master are not the same as the one previously built.

what do you suggest? thx

**Comment by iMichka** [comment]
I think I found it (maybe). In https://github.com/Homebrew/homebrew-science/pull/5771, I completely removed the hdf5 dependency, but it should have stayed there as mandatory dependency. The dylib files are not linked against hdf5. Let me rebuild some bottles.

**Comment by iMichka** [comment]
https://github.com/Homebrew/homebrew-science/pull/5783

**Comment by iMichka** [comment]
Bottles have been updated, please try again. I hope this works now.

**Comment by eolivi** [comment]
thank you a lot !
this build went ok
https://travis-ci.org/openmeeg/openmeeg/jobs/240489593

our two other builds on Mac are not ok.... but it looks like another pb regarding 'brew link'  of openblas:
https://travis-ci.org/openmeeg/openmeeg/builds/240489590?utm_source=github_status

**Comment by eolivi** [comment]
good ! everything green.
Can we close this PR, I've done this one:
https://github.com/openmeeg/openmeeg/pull/205

**Pull request closed without merging**
