### PR TITLE
MAINT: Enable compilation on MSVC

### PR DESCRIPTION
**Pull request by larsoner**
- [x] enable a MSVC-compiled build and get vcpkg to complete so it can be cached
- [x] [show problems](https://github.com/openmeeg/openmeeg/runs/7141207500?check_suite_focus=true) with Range/Ranges/iostream etc.
- [x] revert commits 3a5db7c0a156c7c48d4fe7a917c5fe674d9b09df 9d0106fd4d0f55ed7f7ad5852165ee26be787f43 3a76e33580bfad0837fcfceb4a2c7fe4b68e35d7 61c01e830714cec45e7b3ccd0536124baa8cee3a via 3a5db7c 9d0106f 3a76e33 61c01e8
- [x] fix a [remaining linking bug](https://github.com/openmeeg/openmeeg/runs/7141412732?check_suite_focus=true) with SWIG+MSVC:
    ```
    Creating library D:/a/openmeeg/openmeeg/build/wrapping/python/Release/openmeeg.lib and object D:/a/openmeeg/openmeeg/build/wrapping/python/Release/openmeeg.exp
    openmeegPYTHON_wrap.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl OpenMEEG::Mesh::reference_vertices(class std::map<unsigned int,unsigned int,struct std::less<unsigned int>,class std::allocator<struct std::pair<unsigned int const ,unsigned int> > > const &)" (__imp_?reference_vertices@Mesh@OpenMEEG@@QEAAXAEBV?$map@IIU?$less@I@std@@V?$allocator@U?$pair@$$CBII@std@@@2@@std@@@Z) referenced in function _wrap_Mesh_reference_vertices 
    [D:\a\openmeeg\openmeeg\build\wrapping\python\openmeeg.vcxproj] D:\a\openmeeg\openmeeg\build\wrapping\python\openmeeg\Release\_openmeeg.pyd : fatal error LNK1120: 1 unresolved externals 
    ```
- [x] show msvc green

### CODE REVIEW

**Comment by larsoner** [comment]
Okay https://github.com/openmeeg/openmeeg/runs/7141207500?check_suite_focus=true reproduces the problems I was seeing on conda-forge:
```
BrainVisaTextureIO.obj : error LNK2019: unresolved external symbol "class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl OpenMEEG::maths::operator<<(class std::basic_ostream<char,struct std::char_traits<char> > &,class OpenMEEG::maths::Range const &)" (??6maths@OpenMEEG@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@AEAV23@AEBVRange@01@@Z) referenced in function "public: __cdecl OpenMEEG::maths::BadVector::BadVector(unsigned __int64)" (??0BadVector@maths@OpenMEEG@@QEAA@_K@Z) [D:\a\openmeeg\openmeeg\build\OpenMEEGMaths\OpenMEEGMaths.vcxproj]
```
I can comment out / work around this, but there end up being other problems anyway.

I'm going to try to revert the Range/Ranges/(symmetric)block code to see if it fixes support for MSVC. If it does, then we should try to add that code back in a proper PR with tests passing, rather than via direct commits.

**Comment by larsoner** [comment]
Okay so:

- I reverted four commits (3a5db7c0a156c7c48d4fe7a917c5fe674d9b09df 9d0106fd4d0f55ed7f7ad5852165ee26be787f43 3a76e33580bfad0837fcfceb4a2c7fe4b68e35d7 61c01e830714cec45e7b3ccd0536124baa8cee3a) and things still compiled fine locally on macOS M1, and `cd build && ctest -C $BUILD_TYPE` still passed.
- After looking at how the Windows CIs responded, I made one additional tiny commit (9bb5bfd) to make things work on MSVC [according to the CIs](https://github.com/openmeeg/openmeeg/runs/7143464220?check_suite_focus=true), but I had to skip two of the Python tests due to some unknown path problem that we can hopefully solve later

Reverting commits is never easy, especially when one has in the title "Correct some bugs invisible in the testsuite". But I think it's necessary to make things work with a proper testing/building configuration moving forward.

@agramfort feel free to squash+merge if you agree. Don't forget to change the green button to be a squash+merge to keep history tidy. Then I'll open a separate issue about reincorporating the reverted commits!

**Review by agramfort — APPROVED** [review]

**Comment by agramfort** [comment]
thanks a ton @larsoner 

@papadop now that CIs are green I think you can go back the commits listed above and that fix silent bugs

**Comment by papadop** [comment]
Commits are now re-integrated....

**Comment by papadop** [comment]
For reference these are PRs #498, #501, #502 and #503.

**Comment by papadop** [comment]
I leave it to you to close this PR, if you think it has to be.

**Comment by larsoner** [comment]
It's already closed, no need for anything else here I think. Thanks for reintegrating in a MSVC-compatible way !

**Pull request merged**
